<#
    .SYNOPSIS
        Regenerates docs/FEATURES.md from the feature catalogue and the .reg corpus.

    .DESCRIPTION
        Every feature in Config/Features.json is documented with its command-line
        switch, its description, the exact registry values it writes, how it is
        reverted, and whether it covers new user profiles. Because the content is
        derived from the catalogue and the .reg files themselves, the reference cannot
        drift from what the script actually does - Tests/FeatureDocs.Tests.ps1 fails if
        a feature is added without regenerating this file.

        Run after adding, removing or renaming a feature:
            .\Scripts\Build-FeatureDocs.ps1

    .PARAMETER OutputPath
        Where to write the reference. Defaults to docs/FEATURES.md in the repository.
#>
[CmdletBinding()]
param(
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

$repositoryRoot = Split-Path -Parent $PSScriptRoot
$regfilesPath = Join-Path $repositoryRoot 'Regfiles'
$catalogPath = Join-Path $repositoryRoot 'Config\Features.json'

if (-not $OutputPath) {
    $OutputPath = Join-Path (Join-Path $repositoryRoot 'docs') 'FEATURES.md'
}

<#
    .SYNOPSIS
        Reads a .reg file and returns the operations it performs, in file order.
#>
function Get-DocumentedRegistryOperation {
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    $operations = New-Object System.Collections.Generic.List[object]
    $currentKey = $null

    foreach ($rawLine in (Get-Content -LiteralPath $Path)) {
        $line = $rawLine.Trim()

        if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith(';')) { continue }
        if ($line -match '^Windows Registry Editor Version') { continue }

        if ($line -match '^\[(?<deleted>-)?(?<keyPath>[^\]]+)\]$') {
            $currentKey = $matches.keyPath.Trim()

            if ($matches.deleted -eq '-') {
                $operations.Add([PSCustomObject]@{
                    Key = $currentKey; Value = ''; Data = 'the whole key is deleted'
                })
            }

            continue
        }

        if ($null -eq $currentKey) { continue }

        if ($line -match '^(?<valueName>@|"[^"]+")\s*=\s*(?<data>.+)$') {
            $valueName = if ($matches.valueName -eq '@') { '(Default)' } else { $matches.valueName.Trim('"') }
            $data = $matches.data.Trim()

            if ($data -eq '-') {
                $data = 'the value is deleted'
            }
            elseif ($data -match '^dword:(?<hex>[0-9a-fA-F]+)$') {
                $data = [string][Convert]::ToInt64($matches.hex, 16)
            }

            $operations.Add([PSCustomObject]@{ Key = $currentKey; Value = $valueName; Data = $data })
        }
    }

    return $operations
}

function ConvertTo-AnchorLink {
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Heading)

    $anchor = $Heading.ToLowerInvariant() -replace '[^a-z0-9 -]', '' -replace ' ', '-'
    return $anchor
}

$catalog = Get-Content -LiteralPath $catalogPath -Raw | ConvertFrom-Json
$features = @($catalog.Features)

# Order categories as the catalogue declares them, then anything unexpected, then
# features with no category at all.
$categoryNames = @($catalog.Categories | ForEach-Object { $_.Name })
$usedCategories = @($features | Where-Object { $_.Category } | ForEach-Object { $_.Category } | Select-Object -Unique)
$orderedCategories = @($categoryNames | Where-Object { $usedCategories -contains $_ })
$orderedCategories += @($usedCategories | Where-Object { $categoryNames -notcontains $_ })

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Win11Debloat feature reference')
$lines.Add('')
$lines.Add('> Generated by `Scripts/Build-FeatureDocs.ps1` from `Config/Features.json` and the')
$lines.Add('> `Regfiles/` corpus. Do not edit by hand - rerun the script after changing a feature.')
$lines.Add('')
$lines.Add("This reference lists every setting Win11Debloat can apply, the command-line switch that")
$lines.Add("selects it, and the exact registry values it writes, so you can see precisely what a")
$lines.Add("setting does before you run it.")
$lines.Add('')
$lines.Add("$($features.Count) settings across $($orderedCategories.Count) categories.")
$lines.Add('')
$lines.Add('## Contents')
$lines.Add('')

foreach ($category in $orderedCategories) {
    $count = @($features | Where-Object { $_.Category -eq $category }).Count
    $lines.Add("- [$category](#$(ConvertTo-AnchorLink -Heading $category)) ($count)")
}

$uncategorised = @($features | Where-Object { -not $_.Category })
if ($uncategorised.Count -gt 0) {
    $lines.Add("- [Other settings](#other-settings) ($($uncategorised.Count))")
}

$lines.Add('')

function Add-FeatureSection {
    param(
        [Parameter(Mandatory)]$Feature,
        [Parameter(Mandatory)]$Lines
    )

    $Lines.Add("### $($Feature.Label)")
    $Lines.Add('')
    $Lines.Add("``-$($Feature.FeatureId)``")
    $Lines.Add('')

    if ($Feature.ToolTip) {
        $Lines.Add([string]$Feature.ToolTip)
        $Lines.Add('')
    }

    if ($Feature.MinVersion -or $Feature.MaxVersion) {
        $range = if ($Feature.MinVersion -and $Feature.MaxVersion) {
            "Windows builds $($Feature.MinVersion) to $($Feature.MaxVersion)"
        }
        elseif ($Feature.MinVersion) { "Windows build $($Feature.MinVersion) and newer" }
        else { "Windows build $($Feature.MaxVersion) and older" }

        $Lines.Add("*Only offered on $range.*")
        $Lines.Add('')
    }

    if (-not $Feature.RegistryKey) {
        $Lines.Add('This setting is applied by dedicated logic in the script rather than by a registry file.')
        $Lines.Add('')
        return
    }

    $applyPath = Join-Path $script:RegfilesPathForDocs $Feature.RegistryKey

    if (-not (Test-Path -LiteralPath $applyPath)) {
        $Lines.Add("Registry file ``$($Feature.RegistryKey)`` is missing from the repository.")
        $Lines.Add('')
        return
    }

    $Lines.Add("Registry changes (``$($Feature.RegistryKey)``):")
    $Lines.Add('')
    $Lines.Add('| Key | Value | Set to |')
    $Lines.Add('| --- | --- | --- |')

    foreach ($operation in (Get-DocumentedRegistryOperation -Path $applyPath)) {
        $valueCell = if ($operation.Value) { "``$($operation.Value)``" } else { '' }
        $Lines.Add("| ``$($operation.Key)`` | $valueCell | $($operation.Data) |")
    }

    $Lines.Add('')

    if ($Feature.RegistryUndoKey) {
        $Lines.Add("Reverting: unchecking this setting applies ``$($Feature.RegistryUndoKey)``.")
    }
    else {
        $Lines.Add('Reverting: this setting has no undo file and cannot be reverted by the script.')
    }

    $sysprepPath = Join-Path (Join-Path $script:RegfilesPathForDocs 'Sysprep') $Feature.RegistryKey
    if (Test-Path -LiteralPath $sysprepPath) {
        $Lines.Add('')
        $Lines.Add('New user profiles: covered when running in Sysprep mode.')
    }

    $Lines.Add('')
}

$script:RegfilesPathForDocs = $regfilesPath

foreach ($category in $orderedCategories) {
    $lines.Add("## $category")
    $lines.Add('')

    foreach ($feature in @($features | Where-Object { $_.Category -eq $category })) {
        Add-FeatureSection -Feature $feature -Lines $lines
    }
}

if ($uncategorised.Count -gt 0) {
    $lines.Add('## Other settings')
    $lines.Add('')
    $lines.Add('These are selected through dedicated command-line switches rather than the settings list.')
    $lines.Add('')

    foreach ($feature in $uncategorised) {
        Add-FeatureSection -Feature $feature -Lines $lines
    }
}

$outputDirectory = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDirectory)) {
    New-Item -Path $outputDirectory -ItemType Directory -Force | Out-Null
}

Set-Content -LiteralPath $OutputPath -Value $lines -Encoding UTF8
Write-Host "Wrote $($features.Count) features to $OutputPath"
